#' Fit a mixture of Gaussians to a chromatogram curve and choose the 
#' best-fitting model
#'
#' Fit mixtures of one or more Gaussians to the curve formed by a chromatogram
#' profile, and choose the best fitting model using an information criterion
#' of choice. 
#' 
#' @param chromatogram a numeric vector corresponding to the chromatogram trace
#' @param max_gaussians the maximum number of Gaussians to fit; defaults to 5.
#' Note that Gaussian mixtures with more parameters than observed (i.e., 
#' non-zero or NA) points will not be fit. 
#' @param criterion the criterion to use for model selection;
#'  one of "AICc" (corrected AIC, and default), "AIC", or "BIC"
#'
#' @return a list with three entries: the number of Gaussians used to fit
#' the curve in the best model, the R^2 of that fit, and the fit object 
#' generated by \code{nls}
#'
#' @export
choose_gaussians <- function(chromatogram, max_gaussians = 5, 
                             criterion = c("AICc", "AIC", "BIC")) {
  criterion <- match.arg(criterion)
  
  # clean chromatogram by replacing zeroes and NAs with random noise
  nas <- is.na(chromatogram) | chromatogram == 0
  chromatogram[nas] <- runif(sum(nas), min = 0, max = 0.001)
  
  # don't fit mixtures with more parameters than (experimental) points
  max_gaussians <- min(max_gaussians, floor(sum(!nas) / 3))
  
  # fit and choose models 
  fits <- list()
  for (n_gaussians in seq_len(max_gaussians))
    fits[[n_gaussians]] <- fit_gaussians(chromatogram, n_gaussians)
  models <- purrr::map(fits, "fit")
  if (criterion == "AICc") {
    criteria <- lapply(models, nls_aicc)
  } else if (criterion == "AIC") { 
    criteria <- lapply(models, stats::AIC)
  } else if (criterion == "BIC") {
    criteria <- lapply(models, stats::BIC)  
  }
  best <- fits[[which.min(criteria)]]
  return(best)
} 
